# coding: utf-8

"""
    SpaceTraders API

    SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   

    The version of the OpenAPI document: 2.3.0
    Contact: joel@spacetraders.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetraders_api_client.models.install_ship_module201_response_data_transaction import InstallShipModule201ResponseDataTransaction

class TestInstallShipModule201ResponseDataTransaction(unittest.TestCase):
    """InstallShipModule201ResponseDataTransaction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InstallShipModule201ResponseDataTransaction:
        """Test InstallShipModule201ResponseDataTransaction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InstallShipModule201ResponseDataTransaction`
        """
        model = InstallShipModule201ResponseDataTransaction()
        if include_optional:
            return InstallShipModule201ResponseDataTransaction(
                waypoint_symbol = '',
                ship_symbol = '',
                trade_symbol = '',
                total_price = 56,
                timestamp = ''
            )
        else:
            return InstallShipModule201ResponseDataTransaction(
                waypoint_symbol = '',
                ship_symbol = '',
                trade_symbol = '',
                total_price = 56,
                timestamp = '',
        )
        """

    def testInstallShipModule201ResponseDataTransaction(self):
        """Test InstallShipModule201ResponseDataTransaction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
