# coding: utf-8

"""
    SpaceTraders API

    SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   

    The version of the OpenAPI document: 2.3.0
    Contact: joel@spacetraders.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetraders_api_client.models.install_ship_module201_response_data import InstallShipModule201ResponseData

class TestInstallShipModule201ResponseData(unittest.TestCase):
    """InstallShipModule201ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InstallShipModule201ResponseData:
        """Test InstallShipModule201ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InstallShipModule201ResponseData`
        """
        model = InstallShipModule201ResponseData()
        if include_optional:
            return InstallShipModule201ResponseData(
                agent = spacetraders_api_client.models.agent.Agent(
                    account_id = '0', 
                    symbol = '012', 
                    headquarters = '0', 
                    credits = 56, 
                    starting_faction = '0', 
                    ship_count = 56, ),
                modules = [
                    spacetraders_api_client.models.ship_module.ShipModule(
                        symbol = 'MODULE_MINERAL_PROCESSOR_I', 
                        capacity = 0, 
                        range = 0, 
                        name = '', 
                        description = '', 
                        requirements = spacetraders_api_client.models.ship_requirements.ShipRequirements(
                            power = 56, 
                            crew = 56, 
                            slots = 56, ), )
                    ],
                cargo = spacetraders_api_client.models.ship_cargo.ShipCargo(
                    capacity = 0, 
                    units = 0, 
                    inventory = [
                        spacetraders_api_client.models.ship_cargo_item.ShipCargoItem(
                            symbol = 'PRECIOUS_STONES', 
                            name = '', 
                            description = '', 
                            units = 1, )
                        ], ),
                transaction = spacetraders_api_client.models.install_ship_module_201_response_data_transaction.install_ship_module_201_response_data_transaction(
                    waypoint_symbol = '', 
                    ship_symbol = '', 
                    trade_symbol = '', 
                    total_price = 56, 
                    timestamp = '', )
            )
        else:
            return InstallShipModule201ResponseData(
                agent = spacetraders_api_client.models.agent.Agent(
                    account_id = '0', 
                    symbol = '012', 
                    headquarters = '0', 
                    credits = 56, 
                    starting_faction = '0', 
                    ship_count = 56, ),
                modules = [
                    spacetraders_api_client.models.ship_module.ShipModule(
                        symbol = 'MODULE_MINERAL_PROCESSOR_I', 
                        capacity = 0, 
                        range = 0, 
                        name = '', 
                        description = '', 
                        requirements = spacetraders_api_client.models.ship_requirements.ShipRequirements(
                            power = 56, 
                            crew = 56, 
                            slots = 56, ), )
                    ],
                cargo = spacetraders_api_client.models.ship_cargo.ShipCargo(
                    capacity = 0, 
                    units = 0, 
                    inventory = [
                        spacetraders_api_client.models.ship_cargo_item.ShipCargoItem(
                            symbol = 'PRECIOUS_STONES', 
                            name = '', 
                            description = '', 
                            units = 1, )
                        ], ),
                transaction = spacetraders_api_client.models.install_ship_module_201_response_data_transaction.install_ship_module_201_response_data_transaction(
                    waypoint_symbol = '', 
                    ship_symbol = '', 
                    trade_symbol = '', 
                    total_price = 56, 
                    timestamp = '', ),
        )
        """

    def testInstallShipModule201ResponseData(self):
        """Test InstallShipModule201ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
